### ISSUE TITLE
(docs): basic-pubsub serverless app not found

### ISSUE THREAD

**Issue by pradoz** [aws-samples/aws-iot-esp32-arduino-examples#3]
This part of README.md points to an AWS Serverless App Repository which seems to be inaccessible. The link returns the message:
`The application you were looking for could not be found. Return to the applications search page.`

## Examples:

- **basic-pubsub**: Connects to AWS IoT. Demonstrates subscribing to and publishing to topics. Works great with the [lambda-iot-rule](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-2:826492788183:applications~lambda-iot-rule) serverless application.

------------------------------------------------------

Things I tried:
- Following the link directly from the [guide here](https://aws.amazon.com/blogs/compute/building-an-aws-iot-core-device-using-aws-serverless-and-an-esp32/)
- Searching the SAR for "lambda-iot-rule" and other variations.

I have an AWS support ticket open for this and will report back when I get a response.

**Follow up**
AWS support classified this as a technical issue, which is strange because the app is missing from the SAR entirely.

I will start a repo in CDK that aims to recreate the deployment process. Please leave a comment if you would like to assist me.

**Comment by eddeyonline** [comment]
I have the same issue. It would be great if this app were added again or another way of getting the functionality of this app were included in the guide.
